### ISSUE TITLE
The Video is running when the windows is in the background

### ISSUE THREAD

**Issue by bsxz0604** [bfred-it/iphone-inline-video#122] opened 2017-06-01 05:15 UTC
i met this problem and i used windows.blur , but it does't work.

can you help me or give some idea to fix it

**Comment by bfred-it** [comment] 2017-06-01 05:19
Duplicate of #63. There's more information in there

**Closed by bfred-it** 2017-06-01 05:19 UTC

**Comment by bsxz0604** [comment] 2017-06-01 07:43
eh...so sorry i have fixed it . when document.hidden, can use video.load() to fix it
